### ISSUE TITLE
Help detect if I can default a move constructor

### ISSUE THREAD

**Issue by akrzemi1** [boostorg/config#189]
The following program fails to compile on GCC 4.4 and MSVC 12:

```c++
#include <boost/config.hpp>

#if (!defined BOOST_NO_CXX11_DEFAULTED_FUNCTIONS) && (!defined BOOST_NO_CXX11_RVALUE_REFERENCES)
static_assert(true, "***");
#else
static_assert(false, "***");
#endif

struct X
{
    X(X&&) = default;
};

int main() {}
```

Here is a Wandbox demo: https://wandbox.org/permlink/X5m8jmU18Fvo2Y86

Boost.Config detects support for rvalue references and for defaulted functions, but defaulting a move constructor as defaulted is still a compiler error. Can we define a config macro for that?

**Comment by jzmaddock** [comment]
Care to file a PR?  Instructions for adding new macros are here: http://www.boost.org/doc/libs/1_65_1/libs/config/doc/html/boost_config/guidelines_for_boost_authors.html#boost_config.guidelines_for_boost_authors.adding_new_defect_macros

**Comment by akrzemi1** [comment]
Here we go: https://github.com/boostorg/config/pull/205

**Comment by jzmaddock** [comment]
PR is merged (thanks) so closing down...
