### ISSUE TITLE
cstdint.hpp:303:195: warning: use of C++11 long long integer constant

### ISSUE THREAD

**Issue by jeking3** [boostorg/config#190]
While building Boost.Uuid through Appveyor for cygwin with `cxxflags=-std=c++03`, I am seeing this warning over 1,500 times:
```
./boost/cstdint.hpp:303:195: warning: use of C++11 long long integer constant [-Wlong-long]
 #    elif (defined(ULLONG_MAX) && ULLONG_MAX == 18446744073709551615ULL) || (defined(ULONG_LONG_MAX) && ULONG_LONG_MAX == 18446744073709551615ULL) || (defined(ULONGLONG_MAX) && ULONGLONG_MAX == 18446744073709551615ULL)
                                                                                                                                                                                                   ^
```

See build job:
https://ci.appveyor.com/project/jeking3/uuid/build/1.0.114-develop/job/ws6sqg5vvsc20j1b

**Comment by jzmaddock** [comment]
At first glance I don't see an easy fix - any ideas?

**Comment by lakshayg** [comment]
I am unable to reproduce this issue locally but found this on SO: https://stackoverflow.com/a/33646357/3033441



> It seems that the C++11 warning when using the ll suffix may be a gcc bug.
> 
> A workaround (inspired by @nate-eldredge's comment) is to avoid using the literal and have it produced at compile time with constexpr:
> ```
> int64_t constexpr const trillion = int64_t(1'000'000) * int64_t(1'000'000);
> if(nanoseconds < trillion) ...
> ```

**Comment by Lastique** [comment]
Maybe try silencing the warning with a `#pragma`?

**Comment by jzmaddock** [comment]
Yep, there is actually a #pragma system_header in there already, but I've moved it to catch more cases.

BTW I'm unable to reproduce the original issue, even with -Wall -pedantic.

See https://github.com/boostorg/config/commit/dca252c0870361a0ab52b247eeaa450a26e4f5dd
