### ISSUE TITLE
BOOST_HAS_PRAGMA_DETECT_MISMATCH with Clang defined by config #pragma but not supported.

### ISSUE THREAD

**Issue by pabristow** [boostorg/config#219]
I am compiling Boost.Math tests (using the jamfile) with Clang 6.0.0 on windows 10 and get this warning

In file included from ..\..\..\boost/function/function_base.hpp:21:
..\..\..\boost/type_index.hpp:37:20: warning: unknown pragma ignored [-Wunknown-pragmas]
#           pragma detect_mismatch( "boost__type_index__abi", "RTTI is used")
                   ^
Clang (and GCC?) do not seem to provide this pragma.

In \modular-boost\libs\type_index\include\boost\type_index.hpp

at line 43

#   ifdef BOOST_HAS_PRAGMA_DETECT_MISMATCH
#       pragma detect_mismatch( "boost__type_index__abi", "RTTI is off - using CTTI")
#   end

(and attempts to suppress with -Wno-unknown-pragmas - elswhere reported to have no effect).

while I:\modular-boost\libs\type_index\include\boost\type_index.hpp  says

// Detecting `-fms-extension` compiler flag assuming that _MSC_VER defined when that flag is used.
#if defined (_MSC_VER) && (__clang_major__ > 3 || (__clang_major__ == 3 && __clang_minor__ >= 4))
#   define BOOST_HAS_PRAGMA_DETECT_MISMATCH
#endif

does not seem to give the expected non-define of BOOST_HAS_PRAGMA_DETECT_MISMATCH

BOOST_HAS_PRAGMA_DETECT_MISMATCH is defined, but using Clang 6.0.0 does not support this pragma.

However perhaps this is intentional and it is better to have this warning (whose significance, if any, I have yet to understand)?

**Comment by jzmaddock** [comment]
I'm unable to reproduce with clang-6 installed in the Visual studio IDE and -W4.  I've just added a test case for this: https://github.com/boostorg/config/commit/39f48141c5d50f6203590e6153a76c042e4c465e

**Comment by jzmaddock** [comment]
Ping?  Do we know what's needed to reproduce?

**Comment by pabristow** [comment]
I no longer have Clang 6 available so cannot reproduce or retest.  But the added test case should reveal if anything is still wrong.
