### ISSUE TITLE
BOOST_NO_CXX17_STD_INVOKE broken

### ISSUE THREAD

**Issue by NAThompson** [boostorg/config#221]
`BOOST_NO_CXX17_STD_INVOKE` does not work on g++-6.4.0 or Apple LLVM version 9.1.0 (clang-902.0.39.1) in C++1z mode, due to the fact that their implementation of C++17 is incomplete.

**Comment by jzmaddock** [comment]
Confirmed for GCC-6.x.  I've updated the test case in develop to check for `invoke_result`, and updated the GCC and msvc configurations.  clang+libc++ will have to wait till I see what fails in the CI tests.

**Comment by jzmaddock** [comment]
See also https://github.com/boostorg/config/pull/98

**Comment by jzmaddock** [comment]
Closing as this should be fixed now.
