### ISSUE TITLE
Request new config macro to detect if basic_iostream has operator void* or not

### ISSUE THREAD

**Issue by jeking3** [boostorg/config#229]
I'm looking for a Boost.Config macro that will allow this to build (on Windows too):
```
#if __cplusplus < 201103L
    BOOST_CHECK_MESSAGE(0 == str.operator void* (),
            "stream does not report failure by operator void* (up to C++11)");
#else
    BOOST_CHECK_MESSAGE(0 == str.operator bool (),
            "stream does not report failure by operator bool (as of C++11)");
#endif
```

**Comment by jzmaddock** [comment]
We don't have a macro for this - do we need one - doesn't either a `static_cast` to `bool` of use in an if-statement work in either case?

**Comment by jeking3** [comment]
It does, so I will close this.  I guess that was the original intention for the change in C++11 to be backwards compatible.  Thanks for the suggestion.
