### ISSUE TITLE
CUDA8.X + Visual C++ 2015 does not require "BOOST_NO_CXX11_NOEXCEPT"

### ISSUE THREAD

**Issue by Chachay** [boostorg/config#230]
I worked around on building NVCaffe 0.15 with VC++2015 & VCPKG boost(1.67) and met this [issue](https://ci.appveyor.com/project/Chachay/caffe/build/0.15.15.1.11/job/2t27xedopwpevwoe). 

```
C:/Tools/vcpkg-export-20180618-223846/installed/x64-windows/include\boost/system/error_code.hpp(240): error C2694: 'const char *boost::system::error_category::std_category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const' 
```

To handle this error, I found out "BOOST_NO_CXX11_NOEXCEPT" is not necessary when you use VC++2015(or other MSVC compiler?) as the back end of NVCC.

What I did: 
https://github.com/Chachay/caffe/blob/93bf1e9d8f1c0b31b21621cf48a5d42e4530b515/cmake/Cuda.cmake#L284

What I would like to suggest to do right:
https://github.com/boostorg/config/blob/9fd87d6d7d7d0966f03d28ddb27149e193328748/include/boost/config/compiler/nvcc.hpp#L53

to

```
#if (BOOST_CUDA_VERSION >= 8000000) && (BOOST_CUDA_VERSION < 8010000) && !defined(_MSC_VER)
```

**Comment by jzmaddock** [comment]
Oh :(

Unfortunately the original bug report that led to that define being set was reproduced using msvc as the host compiler - see https://svn.boost.org/trac/boost/ticket/13049.

**Comment by jzmaddock** [comment]
I don't have CUDA 8 installed at present, and have no great desire to "downgrade", I wonder can you:

* Reproduce the original bug report linked above?
* Does using `#if (BOOST_CUDA_VERSION >= 8000000) && (BOOST_CUDA_VERSION < 8010000) && defined( __CUDA_ARCH__)` fix both the original issue and your test case?  In other words is the workaround required for device code only?

**Comment by Chachay** [comment]
* I could reproduce the original bug under my environment. Just I had to handle [this issue](https://github.com/boostorg/preprocessor/issues/15) at cmake option

* My case is related to `boost::system::error_category::std_category::name` which overrides `std::error_category::name`, and "BOOST_NO_CXX11_NOEXCEPT" is directly harm on this overrides. Making CUDA 8.0 pretend as 8.2 have a [good result](https://ci.appveyor.com/project/Chachay/caffe/build/0.15.15.1.14/job/5wqk175oy7ro99g9). What I suggested was only about compiler code (msvc or GCC...). But I understood that this issue is not so easy...

I didn't get the link between the original bug and BOOST_NO_CXX11_NOEXCEPT. Give me a time to digest..

**Comment by Chachay** [comment]
For my side, no news.. and I stacked at the similar place (yet I do not have enough  knowledge about EDG compiler)

Just switching to CUDA9 would be the easiest solution, but, because Windows CUDA 9's setup.exe does not work stably, if I think of setting up a CI environment on Appveyor, I prefer CUDA8... :S

**Comment by Chachay** [comment]
This issue is out of date
