### ISSUE TITLE
Feature detection for std::size

### ISSUE THREAD

**Issue by NAThompson** [boostorg/config#250]
For the [Catmull-Rom PR](https://github.com/boostorg/math/pull/95), we require C++17 `std::size`. I'm currently simulating C++17 feature support with `requires cxx17_if_constexpr`, which seems to work well enough (though [this failure](https://travis-ci.org/boostorg/math/jobs/447629613) makes the mind boggle). However, it might be nicer to have the exact feature.

**Comment by jzmaddock** [comment]
I think all the major compilers are supporting SD-6 feature detection now (https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations#recs.cpp17) so there's not much point in duplicating that effort.  Can you use `__cpp_lib_nonmember_container_access` ?  You will need to have included one of the std lib container headers, but I think you include `<vector>` anyway for that one?

**Comment by morinmorin** [comment]
You can also use `boost::size` from Boost.Range, I think.
