### ISSUE TITLE
BOOST_OVERRIDE

### ISSUE THREAD

**Issue by Kojoley** [boostorg/config#253]
The question about `BOOST_OVERRIDE` was on mail list a long time ago https://lists.boost.org/Archives/boost/2013/07/205180.php; there also was a PR adding it #82. The macro is still in demand. Can we do about it something? If you wish I could extract `BOOST_OVERRIDE` (and possibly `BOOST_FINAL`) from #82 as a separate small PR.

**Comment by jzmaddock** [comment]
Small separate PR's are far more likely to be accepted, so yes, please do go for it if you wish.

**Comment by glenfe** [comment]
See https://github.com/boostorg/config/pull/329

**Comment by EugeneZelenko** [comment]
Should this issue be closed because #329 was merged?
