### ISSUE TITLE
[[no_unique_address]]

### ISSUE THREAD

**Issue by mglisse** [boostorg/config#257]
Hello,
it would be convenient, for use inside boost, to have a way to use the attribute [[no_unique_address]] when it is available. It could be a macro BOOST_ATTRIBUTE_NO_UNIQUE_ADDRESS, or maybe BOOST_ATTRIBUTE(XXX) that expands to [[XXX]] in C++11 and nothing in C++03 (it shouldn't be necessary to check for C++2a since compilers are supposed to ignore the attributes they don't know about), or any other way that is easy to use.

**Comment by jzmaddock** [comment]
Merged to develop.
