### ISSUE TITLE
add cxx17_deduction_guides

### ISSUE THREAD

**Issue by HDembinski** [boostorg/config#262]
Boost.Histogram optionally supports deduction guides on compilers which support this. Please add a test for deduction guide support in the build system, so that corresponding unit tests are only compiled when the compiler supports deduction guides.

**Comment by jzmaddock** [comment]
See https://github.com/boostorg/config/pull/263

**Comment by HDembinski** [comment]
Nice!

**Comment by jzmaddock** [comment]
Merged to develop.
