### ISSUE TITLE
Missing BOOST_NO_TYPEID if not _CPPRTTI in boost/config/compiler/visualc.hpp

### ISSUE THREAD

**Issue by k15tfu** [boostorg/config#296]
Looks like we forgot to define BOOST_NO_TYPEID if RTTI is disabled for MSVC (/GR- option).

I can prepare a PR.

**Comment by MarcelRaad** [comment]
I don't think that's a bug. Without RTTI, you can use `typeid`. You only cannot use *dynamic* typeid.

**Comment by k15tfu** [comment]
@MarcelRaad Thanks for a quick reply!

But MSDN says you shouldn't (sounds like that) use typeid with /GR disabled:

> You usually need the /GR option when your code uses dynamic_cast Operator or typeid
(https://docs.microsoft.com/en-us/cpp/build/reference/gr-enable-run-time-type-information)

**Comment by k15tfu** [comment]
Okay, I got you: BOOST_NO_RTTI is about dynamic_cast and dynamic typeid (https://www.boost.org/doc/libs/1_71_0/libs/exception/doc/configuration_macros.html), but BOOST_NO_TYPEID is about typeid in general. Thank you!
