### ISSUE TITLE
Documentation link from main documentation page is broken

### ISSUE THREAD

**Issue by madmongo1** [boostorg/config#321]
# Version of Boost: 

1.72

# How to reproduce

* Navigate your browser to https://www.boost.org/doc/libs/1_72_0/
* Find the link to `Config`
* Click

# Outcome

The Config link navigates to https://www.boost.org/doc/libs/1_72_0/libs/config/config.htm which serves a 404

# Expected

The link should point to https://www.boost.org/doc/libs/1_72_0/libs/config/

# Evidence

![image](https://user-images.githubusercontent.com/5172425/73642875-cdbaaa00-4672-11ea-80ad-2249a75657b4.png)

**Comment by glenfe** [comment]
I already fixed this for 1.73 in https://github.com/boostorg/config/commit/3fdb073fc2c203f50aef1668382e5d397e081b08
