### ISSUE TITLE
libs/config/checks/architecture has a Jamroot instead of Jamfile

### ISSUE THREAD

**Issue by pdimov** [boostorg/config#351]
`libs/config/checks/architecture` has a `Jamroot` instead of `Jamfile`, which causes the `.obj` files from the architecture and address model checks to end up in `libs/config/checks/architecture/bin` instead of `bin.v2` as one might expect. The usual expectation is that all temporary build artifacts end up in `bin.v2`, so deleting it achieves a clean slate. But that's not the case here; deleting `bin.v2` does not remove the architecture and address model build artifacts, which causes subtle problems when e.g. the default address model for a toolset changes (I just spend 2 hours or so trying to figure out why my default address model for the msvc toolset is detected as 32 bit when it definitely is 64 bit).

When I rename `Jamroot.jam` to `Jamfile.jam`, everything seems to work OK, with the temporary .obj files ending up in `bin.v2`. But I'm not sure there wasn't some reason to use a `Jamroot` here (even though the comment in the file says `Jamfile`).

**Comment by jzmaddock** [comment]
I honestly have no idea why that was Jamroot rather than Jamfile: looks like Jürgen Hunold lifted this from elsewhere?

**Comment by pdimov** [comment]
The copyright in the files says "Steven Watanabe" (@swatanabe). Could have been a standalone example at one point.

I'm 99.4% sure that `Jamfile` is correct here, the only question is whether it will break something. So far everything seems to work locally.

**Comment by pdimov** [comment]
OK, here's the formal pull request: https://github.com/boostorg/config/pull/352.

**Comment by pdimov** [comment]
Fixed now.
