### ISSUE TITLE
Wrong BOOST_NO_CXX11_HDR_ATOMIC on Clang <= 3.6 with libstdc++

### ISSUE THREAD

**Issue by Kojoley** [boostorg/config#367]
The comment here is totally wrong:
https://github.com/boostorg/config/blob/1c45d765f107e0fcfc45a075c55bd66780e98188/include/boost/config/stdlib/libstdcpp3.hpp#L306-L309
At least Clang 3.1+ is fine with libstdc++ atomics header https://wandbox.org/permlink/ceHWsOeXdmKrygap. Probably, the comment was related to a libstdc++ quirk that requires to link with the atomics library when you are using types that requires locking (>64bit on x86 https://wandbox.org/permlink/7YQyjeXK3LvNLeLV), but GCC has the same problem (while Clang 3.7+ learned to link the needed library automatically). I even had to solve that with B2 https://github.com/boostorg/build/issues/419

**Comment by Lastique** [comment]
I think, this might depend on the libstdc++ version in question. Maybe, there is a combination that doesn't work.

PS: The change was made in f9bfac12976abe36667c3465063bd505b9878cab.

**Comment by jzmaddock** [comment]
Looks like I was the guilty party for the comment/commit, I'm sure this is related to the libstdc++ version, and there are so many permutations here that it's hard to know where to begin.

The current situation is possibly over-conservative, but I'm also wondering why anyone would care that much about ancient clang?

**Comment by Kojoley** [comment]
I am not sure if a compiler released 5 years ago is ancient, but it is on regression matrix and I get warnings there from Boost.Math usage.

**Comment by jzmaddock** [comment]
Oh :(  Those will be hard errors when the tests cycle as Math is now C++11 only.
