### ISSUE TITLE
Autolink not working in VS2022 vs 17.0.6

### ISSUE THREAD

**Issue by AubreyOlefile** [boostorg/config#425]
Have to specify full bath for each .lib , eg (x64) for it to build for x64 config.

**Comment by Lastique** [comment]
Autolinked libraries are searched in one of the library paths specified in the linker command line. See [/LIBPATH](https://learn.microsoft.com/en-us/cpp/build/reference/libpath-additional-libpath?view=msvc-170). Make sure you added library paths in your project.

**Comment by jzmaddock** [comment]
Closing on the assumption that this is expected behaviour.
