### ISSUE TITLE
BOOST_HAS_INT128 not defined on clang-cl

### ISSUE THREAD

**Issue by pdimov** [boostorg/config#438]
https://github.com/boostorg/config/blob/1cff5e37bb69f42ffab73438de61e34c71258f19/include/boost/config/compiler/clang.hpp#L101-L103 checks for clang-cl and does not define BOOST_HAS_INT128 if so. But clang-cl does have __int128 (under 64 bit, as usual.) Why are we not defining HAS_INT128?

**Comment by Lastique** [comment]
Note that even the "usual" clang has [problems](https://github.com/boostorg/atomic/blob/581dd7953f467c938aeb7d17f9ff32e3269e3fbe/.github/workflows/ci.yml#L241) with `__int128`. If it is to be enabled for clang-cl, the support needs to be tested, and there should probably be a compiler version check.

**Comment by pdimov** [comment]
I think that the reason the macro isn't defined for clang-cl is that library support is missing (but I have no idea what this library support entails.)

But this isn't useful when you just want to know whether the type exists (along with the built-in arithmetic operations of course) - which it does under clang-cl.

**Comment by jzmaddock** [comment]
The thing is, __int128 *is a* library.  So yes the type exists, and it will compile arithmetic operations, but then you get linker errors because the actual software routines which perform say division aren't available.  So in practice you can't actually use the type in a program... unless you know otherwise?

**Comment by pdimov** [comment]
You're right, division doesn't work on clang-cl (undefined reference to `__divti3`.)
