### ISSUE TITLE
Missing define BOOST_NO_CXX11_NULLPTR on OSX with libstdc++

### ISSUE THREAD

**Issue by Flamefire** [boostorg/config#462]
A build on XCode 9.4.1 on [Drone](https://drone.cpp.al/boostorg/boost-ci/341/38/2) fails because the standard library (stdlibc++) is lacking the `std::nullptr_t` type.

I believe this means that `BOOST_NO_CXX11_NULLPTR` should be defined but is not. It seems to be possible that the compiler supports the `nullptr` keyword but just that the standard library is to old.

See also https://github.com/CPPAlliance/drone-ci/issues/15

**Comment by jzmaddock** [comment]
Now fixed in develop.  I did not fix up C++17 compiler support though - the ancient std lib will likely cause unfixable issues.

**Comment by Flamefire** [comment]
Thanks!
